### ISSUE TITLE
for matplotlib 3.8.x, import error

### ISSUE THREAD

**Issue by anaoravitan** [nschloe/tikzplotlib#598] opened 2024-03-06 15:28 UTC
I downloaded the 0.10.1 version of tikzplotlib. Only importing gave me the following error:

`ImportError: cannot import name 'common_texification' from 'matplotlib.backends.backend_pgf'`

I was using matplotlib 3.8.3. Solved it by downgrading matplotlib to 3.7.5.

**Comment by FriedrichFroebel** [comment] 2024-03-06 15:57
Duplicate of #559.

**Closed as completed** 2024-03-06 16:05 UTC
